fix check branch steps [skip ci]

diff --git a/.github/workflows/bump-versions.yml b/.github/workflows/bump-versions.yml
--- a/.github/workflows/bump-versions.yml
+++ b/.github/workflows/bump-versions.yml
@@ -21,13 +21,6 @@ jobs:
     runs-on: ubuntu-latest-16-cores-open
 
     steps:
-      - name: Check branch
-        run: |
-          if [[ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]]; then
-            echo "ERROR This workflow only runs on the main branch."
-            exit 1
-          fi
-
       - name: Generate GH token
         id: generate_token
         uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
@@ -39,6 +32,13 @@ jobs:
         uses: actions/checkout@v3
         with:
           token: ${{ steps.generate_token.outputs.token }}
+
+      - name: Check branch
+        run: |
+          if [[ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]]; then
+            echo "ERROR This workflow only runs on the main branch."
+            exit 1
+          fi
 
       - name: Run our setup
         uses: ./.github/actions/setup
diff --git a/.github/workflows/publish-new.yml b/.github/workflows/publish-new.yml
--- a/.github/workflows/publish-new.yml
+++ b/.github/workflows/publish-new.yml
@@ -39,12 +39,6 @@ jobs:
     runs-on: ubuntu-latest-16-cores-open
 
     steps:
-      - name: Check branch
-        run: |
-          if [[ "$(git rev-parse --abbrev-ref HEAD)" != "production" ]]; then
-            echo "ERROR You must be on the production branch to publish a new version."
-            exit 1
-          fi
       - name: Check inputs
         run: |
           if [[ "${{ inputs.bump_type }}" != "override" ]] && ! [[ -z "${{ inputs.version_override }}" ]]; then
@@ -62,6 +56,13 @@ jobs:
         uses: actions/checkout@v3
         with:
           token: ${{ steps.generate_token.outputs.token }}
+
+      - name: Check branch
+        run: |
+          if [[ "$(git rev-parse --abbrev-ref HEAD)" != "production" ]]; then
+            echo "ERROR You must be on the production branch to publish a new version."
+            exit 1
+          fi
 
       - name: Run our setup
         uses: ./.github/actions/setup
