New release process (again) (#6379) [skip ci]

diff --git a/.github/workflows/publish-new.yml b/.github/workflows/publish-new.yml
--- a/.github/workflows/publish-new.yml
+++ b/.github/workflows/publish-new.yml
@@ -1,4 +1,4 @@
-name: Publish new SDK release from main (minor version bump)
+name: Publish new SDK release from production branch (minor version bump)
 # This bumps the version, updates the changelogs, publishes a GitHub release, and publishes the packages to npm.
 
 # Prevent more than one non-canary npm publishing job from running at the same time
@@ -22,6 +22,10 @@ on:
         type: string
         description: Version Override
         required: false
+      release_notes_url:
+        type: string
+        description: Release Notes Gist URL
+        required: true
 
 defaults:
   run:
@@ -35,6 +39,12 @@ jobs:
     runs-on: ubuntu-latest-16-cores-open
 
     steps:
+      - name: Check branch
+        run: |
+          if [[ "$(git rev-parse --abbrev-ref HEAD)" != "production" ]]; then
+            echo "ERROR You must be on the production branch to publish a new version."
+            exit 1
+          fi
       - name: Check inputs
         run: |
           if [[ "${{ inputs.bump_type }}" != "override" ]] && ! [[ -z "${{ inputs.version_override }}" ]]; then
@@ -53,10 +63,6 @@ jobs:
         with:
           token: ${{ steps.generate_token.outputs.token }}
 
-      - name: Prepare repository
-        # Fetch full git history and tags for auto
-        run: git fetch --unshallow --tags
-
       - name: Run our setup
         uses: ./.github/actions/setup
 
@@ -65,14 +71,13 @@ jobs:
           git config --global user.name 'huppy-bot[bot]'
           git config --global user.email '128400622+huppy-bot[bot]@users.noreply.github.com'
           if [[ "${{ inputs.bump_type }}" == "override" ]]; then
-            yarn tsx ./internal/scripts/publish-new.ts --bump ${{ inputs.version_override }}
+            yarn tsx ./internal/scripts/publish-new.ts --bump ${{ inputs.version_override }} --release_notes_url ${{ inputs.release_notes_url }}
           else
-            yarn tsx ./internal/scripts/publish-new.ts --bump ${{ inputs.bump_type }}
+            yarn tsx ./internal/scripts/publish-new.ts --bump ${{ inputs.bump_type }} --release_notes_url ${{ inputs.release_notes_url }}
           fi
         env:
           GH_TOKEN: ${{ steps.generate_token.outputs.token }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-          HUPPY_TOKEN: ${{ secrets.HUPPY_TOKEN }}
           R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
           R2_ACCESS_KEY_SECRET: ${{ secrets.R2_ACCESS_KEY_SECRET }}
           TLDRAW_BEMO_URL: https://demo.tldraw.xyz
